<Project>

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <!-- Polyfill configuration -->
    <PropertyGroup>
        <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
    </PropertyGroup>

</Project>